// Base colors sourced from mbadolato/iTerm2-Color-Schemes, plus curated Suda themes. Application
// surfaces, borders, muted text, and contrast corrections are derived by ThemeManager.
// Display names use Night/Day; `mode` stays "dark"/"light" for the browser color-scheme API.
globalThis.SudaThemeCatalog = [
  {
    "id": "gruvbox-night",
    "name": "Gruvbox",
    "mode": "dark",
    "background": "#282828",
    "foreground": "#ebdbb2",
    "accent": "#458588",
    "danger": "#cc241d",
    "success": "#98971a",
    "warning": "#d79921"
  },
  {
    "id": "zen-night",
    "name": "*Zen",
    "mode": "dark",
    "background": "#19191b",
    "foreground": "#f5f5f4",
    "accent": "#6ced96",
    "danger": "#e5484d",
    "success": "#30a46c",
    "warning": "#f5a524",
    "customizableAccent": true,
    "tonalSelection": true,
    "overlayAccentWeight": 0.018,
    "overlayBorderAccentWeight": 0.02
  },
  {
    "id": "zen-day",
    "name": "*Zen",
    "mode": "light",
    "background": "#f4f1ed",
    "foreground": "#27272a",
    "accent": "#6ced96",
    "danger": "#e5484d",
    "success": "#30a46c",
    "warning": "#f5a524",
    "customizableAccent": true,
    "tonalSelection": true,
    "overlayAccentWeight": 0.032
  },
  {
    "id": "ayu-night",
    "name": "Ayu",
    "mode": "dark",
    "background": "#0b0e14",
    "foreground": "#bfbdb6",
    "accent": "#53bdfa",
    "danger": "#ea6c73",
    "success": "#7fd962",
    "warning": "#f9af4f"
  },
  {
    "id": "ayu-day",
    "name": "Ayu",
    "mode": "light",
    "background": "#f8f9fa",
    "foreground": "#5c6166",
    "accent": "#3199e1",
    "danger": "#ea6c6d",
    "success": "#6cbf43",
    "warning": "#eca944"
  },
  {
    "id": "black-metal",
    "name": "Black Metal",
    "mode": "dark",
    "background": "#000000",
    "foreground": "#c1c1c1",
    "accent": "#888888",
    "danger": "#486e6f",
    "success": "#dd9999",
    "warning": "#a06666"
  },
  {
    "id": "catppuccin-frappe",
    "name": "Catppuccin Frappe",
    "mode": "dark",
    "background": "#303446",
    "foreground": "#c6d0f5",
    "accent": "#8caaee",
    "danger": "#e78284",
    "success": "#a6d189",
    "warning": "#e5c890"
  },
  {
    "id": "catppuccin-latte",
    "name": "Catppuccin Latte",
    "mode": "light",
    "background": "#eff1f5",
    "foreground": "#4c4f69",
    "accent": "#1e66f5",
    "danger": "#d20f39",
    "success": "#40a02b",
    "warning": "#df8e1d"
  },
  {
    "id": "catppuccin-macchiato",
    "name": "Catppuccin Macchiato",
    "mode": "dark",
    "background": "#24273a",
    "foreground": "#cad3f5",
    "accent": "#8aadf4",
    "danger": "#ed8796",
    "success": "#a6da95",
    "warning": "#eed49f"
  },
  {
    "id": "catppuccin-mocha",
    "name": "Catppuccin Mocha",
    "mode": "dark",
    "background": "#1e1e2e",
    "foreground": "#cdd6f4",
    "accent": "#89b4fa",
    "danger": "#f38ba8",
    "success": "#a6e3a1",
    "warning": "#f9e2af"
  },
  {
    "id": "everforest-night",
    "name": "Everforest",
    "mode": "dark",
    "background": "#232a2e",
    "foreground": "#d3c6aa",
    "accent": "#7fbbb3",
    "danger": "#e67e80",
    "success": "#a7c080",
    "warning": "#dbbc7f"
  },
  {
    "id": "everforest-day",
    "name": "Everforest",
    "mode": "light",
    "background": "#efebd4",
    "foreground": "#5c6a72",
    "accent": "#7fbbb3",
    "danger": "#e67e80",
    "success": "#a7c080",
    "warning": "#dbbc7f"
  },
  {
    "id": "gruvbox-day",
    "name": "Gruvbox",
    "mode": "light",
    "background": "#fbf1c7",
    "foreground": "#3c3836",
    "accent": "#458588",
    "danger": "#cc241d",
    "success": "#98971a",
    "warning": "#d79921"
  },
  {
    "id": "iceberg-night",
    "name": "Iceberg",
    "mode": "dark",
    "background": "#161821",
    "foreground": "#c6c8d1",
    "accent": "#84a0c6",
    "danger": "#e27878",
    "success": "#b4be82",
    "warning": "#e2a478"
  },
  {
    "id": "iceberg-day",
    "name": "Iceberg",
    "mode": "light",
    "background": "#e8e9ec",
    "foreground": "#33374c",
    "accent": "#2d539e",
    "danger": "#cc517a",
    "success": "#668e3d",
    "warning": "#c57339"
  },
  {
    "id": "linear-night",
    "name": "Linear",
    "mode": "dark",
    "background": "#0f0f10",
    "foreground": "#eeeff1",
    "accent": "#5e6ad2",
    "danger": "#e5484d",
    "success": "#30a46c",
    "warning": "#f5a524"
  },
  {
    "id": "linear-day",
    "name": "Linear",
    "mode": "light",
    "background": "#ffffff",
    "foreground": "#44494d",
    "accent": "#475ba1",
    "danger": "#e5484d",
    "success": "#30a46c",
    "warning": "#f5a524"
  },
  {
    "id": "matte-black",
    "name": "Matte Black",
    "mode": "dark",
    "background": "#121212",
    "foreground": "#bebebe",
    "accent": "#e68e0d",
    "danger": "#d35f5f",
    "success": "#ffc107",
    "warning": "#b91c1c"
  },
  {
    "id": "nord-night",
    "name": "Nord",
    "mode": "dark",
    "background": "#2e3440",
    "foreground": "#d8dee9",
    "accent": "#81a1c1",
    "danger": "#bf616a",
    "success": "#a3be8c",
    "warning": "#ebcb8b"
  },
  {
    "id": "nord-day",
    "name": "Nord",
    "mode": "light",
    "background": "#e5e9f0",
    "foreground": "#414858",
    "accent": "#81a1c1",
    "danger": "#bf616a",
    "success": "#a3be8c",
    "warning": "#ebcb8b"
  },
  {
    "id": "oscura-midnight",
    "name": "Oscura Midnight",
    "mode": "dark",
    "background": "#0b0b0f",
    "foreground": "#e6e6e6",
    "accent": "#e6e7a3",
    "danger": "#ff5c5c",
    "success": "#4ebe96",
    "warning": "#d2d714"
  },
  {
    "id": "rose-pine",
    "name": "Rose Pine",
    "mode": "dark",
    "background": "#191724",
    "foreground": "#e0def4",
    "accent": "#9ccfd8",
    "danger": "#eb6f92",
    "success": "#31748f",
    "warning": "#f6c177"
  },
  {
    "id": "rose-pine-dawn",
    "name": "Rose Pine Dawn",
    "mode": "light",
    "background": "#faf4ed",
    "foreground": "#575279",
    "accent": "#56949f",
    "danger": "#b4637a",
    "success": "#286983",
    "warning": "#ea9d34"
  },
  {
    "id": "solarized-night",
    "name": "Solarized",
    "mode": "dark",
    "background": "#002b36",
    "foreground": "#839496",
    "accent": "#268bd2",
    "danger": "#dc322f",
    "success": "#859900",
    "warning": "#b58900"
  },
  {
    "id": "solarized-day",
    "name": "Solarized",
    "mode": "light",
    "background": "#fdf6e3",
    "foreground": "#657b83",
    "accent": "#268bd2",
    "danger": "#dc322f",
    "success": "#859900",
    "warning": "#b58900"
  },
  {
    "id": "tokyonight-night",
    "name": "TokyoNight",
    "mode": "dark",
    "background": "#1a1b26",
    "foreground": "#c0caf5",
    "accent": "#7aa2f7",
    "danger": "#f7768e",
    "success": "#9ece6a",
    "warning": "#e0af68"
  },
  {
    "id": "tokyonight-day",
    "name": "TokyoNight",
    "mode": "light",
    "background": "#e1e2e7",
    "foreground": "#3760bf",
    "accent": "#2e7de9",
    "danger": "#f52a65",
    "success": "#587539",
    "warning": "#8c6c3e"
  },
  {
    "id": "true-black",
    "name": "True Black",
    "mode": "dark",
    "background": "#000000",
    "foreground": "#f5f5f5",
    "accent": "#ffffff",
    "danger": "#e5484d",
    "success": "#30a46c",
    "warning": "#f5a524"
  },
  {
    "id": "vesper",
    "name": "Vesper",
    "mode": "dark",
    "background": "#101010",
    "foreground": "#ffffff",
    "accent": "#aca1cf",
    "danger": "#f5a191",
    "success": "#90b99f",
    "warning": "#e6b99d"
  }
];
